language: cpp
compiler:
  - gcc
before_install:
# As of this writing (10 May 2014) the Travis build environment is Ubuntu 12.04,
# which needs the following ugly dependency incantations to build RocksDB:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq
 - sudo apt-get install libboost-dev
script: make 
branches:
  only:
    - master
notifications:
  recipients:
    - yinqiwen@gmail.com
  email:
    on_success: change
    on_failure: always
os:
  - linux
